# Name of our workflow
name: 'Test'

# Events that will trigger our workflow
on: [ 'pull_request', 'push' ]

# List of custom jobs
jobs:
  # Job is called "test"
  test:
    # Using a "label" to assign job to a specific hosted runner
    runs-on: ubuntu-latest
    steps:
      # Checks-out our repository under "$GITHUB_WORKSPACE", so our job can access it
      - name: 'Checkout repository'
        uses: actions/checkout@v3

      # Install the requirements
      - name: 'Install'
        run: npm install

      # # Runs commands using the runners shell
      # - name: 'Run tests'
      #   run: npx nyc ava && npx nyc report --reporter cobertura --reporter json-summary

      - name: 'compile'
        run: npm run compile

      # - name: Code Coverage Report
      #   uses: irongut/CodeCoverageSummary@v1.3.0
      #   with:
      #     filename: ./coverage/cobertura-coverage.xml
      #     badge: true
      #     fail_below_min: true
      #     format: markdown
      #     hide_branch_rate: false
      #     hide_complexity: false
      #     indicators: true
      #     output: both
      #     thresholds: '60 80'
      # - name: Add Coverage PR Comment
      #   uses: marocchino/sticky-pull-request-comment@v2
      #   if: github.event_name == 'pull_request'
      #   with:
      #     recreate: true
      #     path: code-coverage-results.md
      # - name: Create Coverage Badges
      #   uses: jaywcjlove/coverage-badges-cli@main
      #   with:
      #     style: flat
      #     source: ./coverage/coverage-summary.json
      #     output: ./coverage/badges.svg
